apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: kushaggarwal/pipeline
          ports:
            - containerPort: 80
