kind: Service
apiVersion: v1
metadata:
  name: servicedeployment
spec:
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
